#!/usr/bin/env bash

# Eject all external drives
BASEDIR=$(dirname "$BASH_SOURCE")

$BASEDIR/notify "Ejecting Drives" "Please wait"
ejected=""

for d in /Volumes/*
do
  if diskutil info "$d" | grep "\bDevice Location:\\s\\+External" > /dev/null
  then
    ejected="$d, $ejected"
    diskutil eject "$d"
  fi
done

$BASEDIR/notify "Drives Ejected" "$ejected"
