#!/usr/bin/env bash

# This script is meant to be called by the crontab once a minute.

# Only tweet 1/192 times this is run (if this is run once a minute, it will
# tweet about once every three hours). Don't tweet on a schedule, because then
# missed tweets (like when my laptop is closed) are more noticeable.
number=$RANDOM
let "number %= 264"

if [ $number = 0 ]; then
  printf "\nRunning haiku_ebooks bash script at $(date)\n"

  chruby 2.4.2

  printf "$(ruby --version)\n"
  printf "$(ruby /Users/spencer/git/fun/haiku_ebooks/bin/haiku_ebooks)\n\n"
else
  printf "Not running haiku_ebooks bash script at $(date), number=$number\n"
fi
