#!/usr/bin/env bash

# Base16 Shell
BASE16_SHELL="/usr/local/opt/zplug/repos/chriskempson/base16-shell/"
[ -s "$BASE16_SHELL/profile_helper.sh" ] && \
    eval "$("$BASE16_SHELL/profile_helper.sh")"

TERM=xterm htop
