#!/usr/bin/env ruby

def indent(uncles)
  uncles.map { |u| u ? '| ' : '  ' }.join + '|-'
end

def tree(dir, uncles)
  return unless File.directory?(dir)

  puts "#{indent(uncles[0...-1])}#{File.basename(dir)}/"

  children = Dir.children(dir).sort

  new_uncle = children.count > 1

  children.each do |item|
    if File.directory?(File.join(dir, item))
      tree File.join(dir, item), uncles + [new_uncle && item != children.last]
    else
      puts "#{indent(uncles)}#{item}"
    end
  end
end

dir = ARGV[0] || '.'

tree dir, [false]
