#!/usr/bin/env bash

# Get path to the directory of this file
BASEDIR=$(dirname "$BASH_SOURCE")

$BASEDIR/notify "Weather Alert" "Started weather_alert"

while true; do
  HOUSE_TEMP=71
  OUTSIDE_TEMP=$($BASEDIR/outside_temperature)
  changed=false

  if [ -s $BASEDIR/windows_closed ]; then
    # The windows are closed
    if [ $OUTSIDE_TEMP -lt $HOUSE_TEMP ]; then
      $BASEDIR/notify "Weather Alert" "It is colder outside, open the windows"
      rm $BASEDIR/windows_closed
      changed=true
    fi
  else
    # The windows are open
    if [ $OUTSIDE_TEMP -gt $HOUSE_TEMP ]; then
      $BASEDIR/notify "Weather Alert" "It is hotter outside, close the windows"
      echo "The windows were closed $(date)" > $BASEDIR/windows_closed
      changed=true
    fi
  fi

  if [ -s $BASEDIR/end_weather_alert ]; then
    rm $BASEDIR/end_weather_alert
    $BASEDIR/notify "Weather Alert" "Goodbye"
    exit 0
  fi

  if [ "$changed" = true ]; then
    sleep 3600 # An hour
  else
    sleep 600 # Ten minutes
  fi
done
