#!/usr/bin/env bash
$BASEDIR/notify "Weather Alert" "Started weather_alert"

while true; do
  # Get path to the directory of this file
  BASEDIR=$(dirname "$BASH_SOURCE")

  source /usr/local/share/chruby/chruby.sh
  chruby 2.3.1

  HOUSE_TEMP=71
  OUTSIDE_TEMP=$($BASEDIR/outside_temperature)
  changed=false

  if [ -s $BASEDIR/windows_closed ]; then
    # The windows are closed
    if [ $OUTSIDE_TEMP -lt $HOUSE_TEMP ]; then
      $BASEDIR/notify "Weather Alert" "It is colder outside, open the windows"
      rm $BASEDIR/windows_closed
      changed=true
    fi
  else
    # The windows are open
    if [ $OUTSIDE_TEMP -gt $HOUSE_TEMP ]; then
      $BASEDIR/notify "Weather Alert" "It is hotter outside, close the windows"
      echo "The windows were closed $(date)" > $BASEDIR/windows_closed
      changed=true
    fi
  fi

  if [ "$changed" = true ]; then
    sleep 3600 # An hour
  else
    sleep 600 # Ten minutes
  fi
done
